import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDownRight, ArrowUpRight, ArrowUp, AudioLines, Check, ChevronDown, ChevronRight, CircleHelp, Database, Download, FileText, LayoutDashboard, Link2, LoaderCircle, MessageSquareText, Pin, Plus, Radio, Settings2, ShieldCheck, Snowflake, Sparkles, Square, Unplug, X } from 'lucide-react';
import type { Answer, Health, Meeting } from '../../../shared/contracts';
import './styles.css';
type State={meeting:Meeting;health:Health;captureStatus:string};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const compact=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',notation:'compact',maximumFractionDigits:2}).format(n);
const samples=['How far below budget was revenue?','How much did EMEA enterprise miss budget?','Show overall gross margin by product'];
async function post(path:string,body:unknown={}){const res=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const data=await res.json();if(!res.ok)throw new Error(data.error||'Request failed');return data;}
function App(){
 const [state,setState]=useState<State>();const [error,setError]=useState('');const [connected,setConnected]=useState(false);const [question,setQuestion]=useState('');const [tab,setTab]=useState<'insights'|'notes'>('insights');const [settings,setSettings]=useState(false);const [parent,setParent]=useState<string>();const [busy,setBusy]=useState(false);const [notes,setNotes]=useState('');const meetingId=useRef('');const transcriptBottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{const source=new EventSource('/api/events');source.onmessage=e=>{const s:State=JSON.parse(e.data);setState(s);setConnected(true);if(meetingId.current!==s.meeting.id){meetingId.current=s.meeting.id;setNotes(s.meeting.notes);setParent(undefined);}};source.onerror=()=>setConnected(false);return()=>source.close();},[]);
 useEffect(()=>{
  transcriptBottom.current?.scrollIntoView({behavior:'smooth',block:'nearest'});
 },[state?.meeting.transcript.length]);
 async function action(path:string,body?:unknown){try{setError('');await post(path,body);}catch(e){setError((e as Error).message);}}
 async function ask(text=question){if(!text.trim()||busy)return;setBusy(true);try{await post('/api/questions',{question:text,parentId:parent});setQuestion('');setParent(undefined);setTab('insights');setError('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 if(!state)return <div className="loading"><Snowflake size={32}/><h2>Opening your meeting room</h2><p>{connected?'Loading…':'Connecting to the local server…'}</p></div>;
 const {meeting,health}=state;const answered=meeting.answers.filter(a=>a.status==='answered').length;const pinned=meeting.answers.filter(a=>a.pinned).length;const running=meeting.answers.some(a=>a.status==='querying');const setupComplete=health.cortexConfigured&&health.snowflakeConfigured&&health.zoomConfigured&&health.liveEnabled;
 return <div className="shell">
  <aside className="sidebar">
   <a className="brand" href="/"><div className="brand-icon"><AudioLines size={23}/></div><span>coco<span className="brand-dot">.</span></span></a>
   <div className="workspace"><div className="company-mark">M</div><div><strong>Meridian Cloud</strong><small>Finance workspace</small></div><ChevronDown size={15}/></div>
   <div className="nav-label">WORKSPACE</div>
   <button className="nav-item selected" onClick={()=>setTab('insights')}><LayoutDashboard size={18}/>Meeting room<span className="nav-pill">1</span></button>
   <button className="nav-item" onClick={()=>setTab('notes')}><FileText size={18}/>Meeting notes{pinned>0&&<span className="nav-pill">{pinned}</span>}</button>
   <button className="nav-item" onClick={()=>setSettings(true)}><Database size={18}/>Connections<small className="status-dot amber"/></button>
   <div className="sidebar-meeting"><div className="nav-label">CURRENT SESSION</div><div className="session-name"><span className="status-dot"/> Q3 business review</div><span className="session-sub">Finance · Q3 2026</span></div>
   <div className="sidebar-bottom"><div className="sidebar-tip"><Sparkles size={18}/><p>Stay in the conversation.<br/><strong>We’ll handle the numbers.</strong></p></div><button className="profile" onClick={()=>setSettings(true)}><span className="avatar">T</span><span><strong>Tejas</strong><small>Live workspace</small></span><Settings2 size={17}/></button></div>
  </aside>
  <div className="workspace-main">
   <header className="topbar"><div><span>Workspace</span><ChevronRight size={14}/><strong>Meeting room</strong></div><div><span className={`connection ${connected?'':'disconnected'}`}><span className="status-dot"/>{connected?'Local server connected':'Reconnecting…'}</span><button className="icon-button" aria-label="Connection settings" onClick={()=>setSettings(true)}><Settings2 size={18}/></button></div></header>
   <main>
    <div className="page-heading"><div><div className="eyebrow">MEETING INTELLIGENCE</div><h1>Room for better questions.</h1><p>Your conversation, connected to the numbers that matter.</p></div><button className="button secondary" disabled={running} onClick={()=>action('/api/meeting/new')}><Plus size={16}/>New meeting</button></div>
    <div className="mode-banner"><div><span className="demo-tag">{setupComplete?'LIVE ANALYSIS':'SETUP REQUIRED'}</span><span>{setupComplete?'CoCo interpretation + Snowflake semantic queries':'Complete the local connection checklist before starting a meeting.'}</span></div><button onClick={()=>setSettings(true)}>Connection setup <ArrowUpRight size={14}/></button></div>
    {error&&<div className="error-banner" role="alert"><CircleHelp size={17}/>{error}<button onClick={()=>setError('')} aria-label="Dismiss error"><X size={16}/></button></div>}
    <div className="meeting-heading"><div className="meeting-title"><div className="meeting-logo"><MessageSquareText size={22}/></div><div><h2>Q3 business review <span className={`badge ${meeting.endedAt?'ended':''}`}>{meeting.endedAt?'Ended':meeting.capture==='zoom'?'Zoom armed':'Ready'}</span></h2><p>Connect your live Zoom meeting and Snowflake semantic view.</p></div></div><div className="meeting-controls"><button className="button secondary compact" onClick={()=>action('/api/capture/zoom')} disabled={!!meeting.endedAt||!setupComplete}><Radio size={15}/>Connect Zoom</button></div></div>
    <div className="meeting-grid">
     <section className="transcript-panel panel"><div className="panel-header"><div><AudioLines size={18}/><h3>Conversation</h3></div><span className="mini-label">{meeting.capture==='idle'?'STANDBY':meeting.capture.toUpperCase()}</span></div><div className="transcript-body">{!meeting.transcript.length?<div className="transcript-empty"><div className="soundwave">{[12,24,40,28,48,32,20,36,14].map((h,i)=><i key={i} style={{height:h}}/>)}</div><h3>Ready for your meeting</h3><p>Complete connection setup, then connect Zoom to receive a live transcript.</p><button onClick={()=>setSettings(true)}>Open setup <ArrowUpRight size={13}/></button><span>Nothing is recorded or analyzed until you arm Zoom capture.</span></div>:meeting.transcript.map((s,i)=><div className={`utterance ${s.text.toLowerCase().includes('coco')?'question-utterance':''}`} key={s.id}><div className={`speaker-avatar s${i%3}`}>{s.speaker[0]}</div><div><div className="speaker-line"><strong>{s.speaker}</strong><time>{new Date(s.timestamp).toLocaleTimeString('en-US',{hour:'2-digit',minute:'2-digit'})}</time></div><p>{s.text}</p>{s.text.toLowerCase().includes('coco')&&<span className="detected"><Sparkles size={11}/>Analyst request</span>}<button className="investigate" onClick={()=>ask(s.text)}>Investigate <ArrowUpRight size={12}/></button></div></div>)}<div ref={transcriptBottom}/></div><div className="transcript-footer"><span className={`status-dot ${meeting.capture==='idle'?'muted':''}`}/><span>{state.captureStatus}</span>{meeting.capture!=='idle'&&<button onClick={()=>action('/api/capture/stop')} aria-label="Stop capture"><Square size={13}/></button>}</div></section>
     <section className="analyst-panel panel"><div className="panel-header"><div className="panel-tabs"><button className={tab==='insights'?'active':''} onClick={()=>setTab('insights')}><Sparkles size={17}/>Live insights{answered>0&&<span>{answered}</span>}</button><button className={tab==='notes'?'active':''} onClick={()=>setTab('notes')}><FileText size={16}/>Notes{pinned>0&&<span>{pinned}</span>}</button></div><span className="semantic-label"><ShieldCheck size={13}/>Semantic context</span></div>
     <div className="insights-body">{tab==='notes'?<div className="notes-view"><div className="notes-heading"><h3>Meeting recap</h3><a className="button secondary compact" href="/api/meeting/export"><Download size={14}/>Export</a></div><p>Pin findings to keep the evidence with the discussion.</p>{meeting.answers.filter(a=>a.pinned).map(a=><div className="pinned-note" key={a.id}><Pin size={15}/><div><strong>{a.headline}</strong><p>{a.interpretation}</p></div></div>)}<label htmlFor="notes">Discussion, decisions & follow-ups</label><textarea id="notes" value={notes} placeholder="Add decisions and action items. Owners and due dates stay yours to confirm." onChange={e=>setNotes(e.target.value)} onBlur={()=>action('/api/meeting/context',{notes})}/><small>Saved when you leave this field. Export includes transcript and pinned evidence.</small><button className="button secondary compact" onClick={async()=>{await action('/api/meeting/context',{notes});await action('/api/meeting/end');}}>End meeting & save notes</button></div>:!meeting.answers.length?<div className="insights-empty"><div className="sparkle-orbit"><Sparkles size={30}/><span/><i/></div><span className="eyebrow">YOUR ANALYST IS READY</span><h2>The question behind the slide.<br/>The answer in the room.</h2><p>Ask about revenue, budget variance, or gross margin.<br/>Every answer comes with its context and evidence.</p><div className="suggestion-list">{samples.map((s,i)=><button key={s} onClick={()=>ask(s)}><span className="suggestion-icon">{i===0?<ArrowDownRight size={17}/>:i===1?<Database size={16}/>:<LayoutDashboard size={16}/>}</span>{s}<ArrowUpRight size={16}/></button>)}</div><span className="grounding"><ShieldCheck size={13}/>Grounded in QBR_FINANCE · 6 defined metrics</span></div>:<div className="answer-list">{[...meeting.answers].reverse().map(a=><AnswerCard key={a.id} answer={a} onPin={()=>action(`/api/answers/${a.id}/pin`)} onCancel={()=>action(`/api/answers/${a.id}/cancel`)} onFollow={()=>{setParent(a.id);setQuestion('Exclude the largest customer');}}/>)}</div>}</div>
     <form className="composer" onSubmit={e=>{e.preventDefault();void ask();}}>{parent&&<div className="parent-chip"><Link2 size={12}/>Following up on selected answer<button type="button" aria-label="Clear follow-up" onClick={()=>setParent(undefined)}><X size={12}/></button></div>}<div className="composer-row"><Sparkles size={18}/><input aria-label="Ask a financial question" placeholder={setupComplete?'Ask a question about the numbers…':'Complete live setup before asking questions'} value={question} onChange={e=>setQuestion(e.target.value)} disabled={!!meeting.endedAt||!setupComplete}/><button className="send-button" disabled={!question.trim()||busy||!!meeting.endedAt||!setupComplete} aria-label="Send question"><ArrowUp size={19}/></button></div><div className="composer-footer"><span><span className="status-dot"/>CoCo + Snowflake</span><label>Context <select aria-label="Current slide topic" value={meeting.topic} onChange={e=>action('/api/meeting/context',{topic:e.target.value})}><option value="revenue">Revenue review</option><option value="margin">Gross margin</option></select></label></div></form>
     </section>
    </div>
    <footer className="page-footer"><span><Snowflake size={13}/>Designed for Snowflake · Independent proof of concept</span><span>Fictional company. Real questions.</span></footer>
   </main>
  </div>
  {settings&&<div className="modal-backdrop" onClick={()=>setSettings(false)}><section className="settings-modal" role="dialog" aria-modal="true" aria-label="Connection setup" onClick={e=>e.stopPropagation()}><button className="modal-close icon-button" onClick={()=>setSettings(false)} aria-label="Close settings"><X size={20}/></button><span className="eyebrow">WORKSPACE CONNECTIONS</span><h2>Connect the live experience.</h2><p>Configure these services in your local .env file to receive real meeting transcripts and Snowflake queries.</p>{[['CoCo Agent SDK',health.cortexConfigured,'CLI installed + named Snowflake connection'],['Snowflake',health.snowflakeConfigured,'Account, user, restricted role, and semantic view'],['Zoom RTMS',health.zoomConfigured,'App credentials, webhook secret, and meeting UUID'],['Live access check',health.liveEnabled,'Verify grants and golden queries before enabling live access']].map(([name,ok,description])=><div className="setup-item" key={String(name)}><div className={ok?'setup-icon ok':'setup-icon'}>{ok?<Check size={18}/>:<Unplug size={18}/>}</div><div><strong>{name}</strong><p>{description}</p></div><span className={ok?'badge':'badge pending'}>{ok?'Configured':'Needed'}</span></div>)}<div className="setup-command"><code>npm run doctor</code><p>Follow <strong>docs/setup.md</strong> and <strong>docs/zoom-rtms.md</strong>. Never enter account credentials in the meeting chat.</p></div><p className="small">Configured status checks local settings only; test your live connection before running a meeting.</p><button className="button primary" onClick={()=>setSettings(false)}>Back to meeting <ArrowUpRight size={15}/></button></section></div>}
 </div>;
}
function AnswerCard({answer:a,onPin,onCancel,onFollow}:{answer:Answer;onPin:()=>void;onCancel:()=>void;onFollow:()=>void}){
 const [details,setDetails]=useState(false);const pending=['queued','querying'].includes(a.status);const rows=a.evidence.find(e=>e.purpose==='Financial breakdown')?.rows??a.evidence[0]?.rows??[];
 const max=Math.max(1,...rows.map(r=>Math.abs(a.plan.metric==='margin'?r.gross_margin??0:r.variance)));
 return <article className={`answer-card ${pending?'pending-card':''}`}><div className="answer-top"><span className="answer-type">{pending?<LoaderCircle size={14} className="spin"/>:<Sparkles size={14}/>} {pending?(a.status==='queued'?'Queued':'Investigating'):a.status==='answered'?'Financial insight':a.status==='needs_clarification'?'Clarification needed':a.status}</span><div>{a.status==='answered'&&<button className={`icon-button ${a.pinned?'is-pinned':''}`} onClick={onPin} aria-label={a.pinned?'Unpin answer':'Pin answer'}><Pin size={15}/></button>}{pending&&<button className="icon-button" onClick={onCancel} aria-label="Cancel investigation"><X size={15}/></button>}</div></div><p className="original-question">{a.question}</p><h3>{pending?'Checking the financial context…':a.headline??a.error}</h3>{a.interpretation&&<p className="interpretation">{a.interpretation}</p>}{a.status==='answered'&&<><div className="answer-stats"><div><span>Actual revenue</span><strong>{money(a.summary!.actual)}</strong></div><div><span>Budget</span><strong>{money(a.summary!.budget)}</strong></div><div><span>{a.plan.metric==='margin'?'Gross margin':'Variance'}</span><strong className={a.summary!.variance<0&&a.plan.metric!=='margin'?'negative':''}>{a.plan.metric==='margin'?`${a.summary!.gross_margin?.toFixed(1)}%`:money(a.summary!.variance)}</strong></div></div>{rows.length>1&&<div className="bar-chart">{rows.slice(0,5).map(r=><div className="bar-row" key={r.label}><span>{r.label}</span><div className="bar-track"><i className={r.variance<0&&a.plan.metric!=='margin'?'bar-negative':''} style={{width:`${Math.max(2,Math.abs(a.plan.metric==='margin'?r.gross_margin??0:r.variance)/max*100)}%`}}/></div><strong>{a.plan.metric==='margin'?`${r.gross_margin?.toFixed(1)}%`:compact(r.variance)}</strong></div>)}{rows.length>5&&<small>Top 5 by actual revenue · full results in evidence</small>}</div>}<div className="answer-footer"><button onClick={()=>setDetails(!details)}><Database size={13}/>Snowflake evidence<ChevronDown size={13}/></button><button onClick={onFollow}>Follow up <ArrowUpRight size={13}/></button></div>{details&&<div className="evidence">{a.evidence.map(e=><div key={e.id}><strong>{e.purpose}</strong><p>{e.queryId?`Query ID: ${e.queryId}`:'No warehouse query ID recorded.'} · {e.durationMs} ms</p><pre>{e.sql}</pre><div className="table-scroll"><table><thead><tr><th>Scope</th><th>Actual</th><th>Budget</th><th>Variance</th></tr></thead><tbody>{e.rows.map(r=><tr key={r.label}><td>{r.label}</td><td>{money(r.actual)}</td><td>{money(r.budget)}</td><td>{money(r.variance)}</td></tr>)}</tbody></table></div></div>)}</div>}</>}</article>;
}
createRoot(document.getElementById('root')!).render(<App/>);
