-- Run with a provisioning identity, never the app's runtime identity.
CREATE DATABASE IF NOT EXISTS COCO_QBR_DEMO;
CREATE SCHEMA IF NOT EXISTS COCO_QBR_DEMO.ANALYTICS;
CREATE WAREHOUSE IF NOT EXISTS COCO_QBR_WH WAREHOUSE_SIZE='XSMALL' AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE;
USE WAREHOUSE COCO_QBR_WH;
CREATE ROLE IF NOT EXISTS COCO_QBR_READER;
CREATE TABLE IF NOT EXISTS COCO_QBR_DEMO.ANALYTICS.FINANCE_MONTHLY (
 MONTH DATE, QUARTER VARCHAR, CUSTOMER_ID VARCHAR, CUSTOMER VARCHAR,
 REGION VARCHAR, SEGMENT VARCHAR, PRODUCT VARCHAR,
 ACTUAL_REVENUE NUMBER(18,2), BUDGET_REVENUE NUMBER(18,2),
 ACTUAL_COGS NUMBER(18,2), BUDGET_COGS NUMBER(18,2),
 PRIMARY KEY (MONTH,CUSTOMER_ID,PRODUCT)
);
GRANT USAGE ON DATABASE COCO_QBR_DEMO TO ROLE COCO_QBR_READER;
GRANT USAGE ON SCHEMA COCO_QBR_DEMO.ANALYTICS TO ROLE COCO_QBR_READER;
GRANT USAGE ON WAREHOUSE COCO_QBR_WH TO ROLE COCO_QBR_READER;
